name: SpigotTest
version: 1.0
api-version: 1.17
main: me.weisboys.randomsurvival.RandomSurvival

commands:
#    randomsurvival:
#        description: main command for randomsurvival
#        usage: /<command> [subcommand] ...
#        permission: randomsurvival.resetcommand
    rstoggle:
        description: enables/disables the plugin
        usage: /<command>
        permission: randomsurvival.togglecommand
    rsnotify:
        description: Enables/disables notification of new mappings
        usage: /<command>
        permission: randomsurvival.notifycommand

permissions:
    randomsurvival.resetcommand: 
        description: the permission to reset random drops manually
    randomsurvival.togglecommand:
        description: the permission to enable/disable the plugin
    randomsurvival.notifycommand:
        description: The permission to enable/disable notifications
